### ISSUE TITLE
DevTools failed to load SourceMap: ..://ljjemllljcmogpfapbkkighbhhppjdbg/build/env.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by zhb124404** [vuejs/devtools#1385]
### Version
6.0.0-beta.7

### Browser and OS info
89.0.4389.90 64bit  (cohort: 89_Win_72)

### Steps to reproduce
just open a vue page served by webpack-dev-server

and then show:
DevTools failed to load SourceMap: Could not load content for chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/build/env.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

### What is expected?
No Warning

### What is actually happening?
In DevTool Console panel :

DevTools failed to load SourceMap: Could not load content for chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/build/env.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by PHenryy** [comment]
same issue

**Comment by cordeiguerin** [comment]
same issue (but I run Linux Mint, rather than Windows)

**Comment by jSadoski** [comment]
Same issue, but on iOS in Chrome and Brave.

**Comment by jSadoski** [comment]
I wanted to follow up with more information about this issue. This breaks the whole extension for me with this error: 

```javascript
Uncaught (in promise) TypeError: Cannot set property '__VUE_DEVTOOLS_UID__' of null
    at registerAppJob (backend.js:1437)
```

```javascript
Uncaught (in promise) TypeError: Cannot read property 'id' of null
    at getComponentInstance (backend.js:3225)
    at Object.sendComponentTreeData (backend.js:3150)
    at Bridge.<anonymous> (backend.js:754)
    at Bridge.emit (backend.js:3720)
    at Bridge._emit (backend.js:1126)
    at backend.js:1058
    at Array.forEach (<anonymous>)
    at backend.js:1058
    at listener (backend.js:2105)
```

**Comment by greaterDeltaCS** [comment]
Found a fix for this. In  developer tools in chrome browser, go to settings(click the gear icon on the same bar as the console tab). Find and uncheck box that says Enable Javascript Sourcemap. exit settings and reload(I did a hard reload/empty cache. The error should be gone.

**Comment by unnsteinngardars** [comment]
> Found a fix for this. In developer tools in chrome browser, go to settings(click the gear icon on the same bar as the console tab). Find and uncheck box that says Enable Javascript Sourcemap. exit settings and reload(I did a hard reload/empty cache. The error should be gone.

Kudos! Did the trick for me.

**Comment by givihuda** [comment]
Can somebody explain what this error means? I can't tell if it's causing the weird issue I'm having while modifying some code I'm not very familiar with that uses Laravel 8 and Vue (v?).

DevTools failed to load SourceMap: Could not load content for http://localhost:8002/js/vue-resize.esm.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

I'm not familiar with vue-resize.esm.js.map... is that a file in the /js folder that Google likes Chrome to look for to help DevTools understand your code?

**Comment by jSadoski** [comment]
> is that a file in the /js folder that Google likes Chrome to look for to help DevTools understand your code?

Yes, source maps helps DevTools unpack your minified code. It's just for when you're running in dev. See: [MDN: Use a Source Map](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map).

As to why this is breaking Vue DevTools I'm not totally sure.

**Comment by redfox05** [comment]
> Found a fix for this. In developer tools in chrome browser, go to settings(click the gear icon on the same bar as the console tab). Find and uncheck box that says Enable Javascript Sourcemap. exit settings and reload(I did a hard reload/empty cache. The error should be gone.

This is a workaround, not a fix, as the likelyhood is that if you are using VueJS DevTools, you are wanting to use sourcemaps, so dont want to untick this option as its a global flag for all sourcemaps.

The actual fix for this is one of two options:
1) Exclude the sourcemap line from the end of the JS file if sourcemaps are not going to be included in the built code.
2) Include the sourcemaps in the extension, and the problem also goes away.

P.s. I got this error for the utils.js script instead:

`DevTools failed to load source map: Could not load content for chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/build/util.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME`

**Comment by givihuda** [comment]
Since I'm not very familiar with the Vue implementation on the project I referenced, I'm not sure the previous developers even implemented the sourcemap or Vue or whatever properly to begin with. I will be able to determine this better with more review of the code, which I can do when I use the project again, and if I find anything useful there that would be helpful for this thread, I'll post here again. Thanks for the info.

**Comment by uonick** [comment]
> I got this error for the utils.js script instead:

Same issue on `macOS (Big Sur 11.5)` `Chrome (Version 92.0.4515.107 (Official Build) (x86_64))` and `Vue.js devtools
6.0.0 beta 15` + `ViteJS (2.4.3)`

![image](https://user-images.githubusercontent.com/365029/127386879-513bc0a9-afba-469a-b8b1-1e07372280c9.png)

**Comment by 9mm** [comment]
Just started getting this as well

**Comment by geminigeek** [comment]
> > I got this error for the utils.js script instead:
> 
> Same issue on `macOS (Big Sur 11.5)` `Chrome (Version 92.0.4515.107 (Official Build) (x86_64))` and `Vue.js devtools 6.0.0 beta 15` + `ViteJS (2.4.3)`
> 
> ![image](https://user-images.githubusercontent.com/365029/127386879-513bc0a9-afba-469a-b8b1-1e07372280c9.png)

Same issue here on win10

**Comment by Akryum** [comment]
Source maps are not generated for the production build of the devtools extension:

![image](https://user-images.githubusercontent.com/2798204/133919184-785329ec-067a-45ea-84c5-58990e58dd07.png)

**Comment by glen-84** [comment]
I'm still seeing these warnings ...

> DevTools failed to load source map: Could not load content for chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/build/fast-copy.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by givihuda** [comment]
If source maps are not generated for the production build of the devtools extension, then why does the production version check for source maps? It seems like it guarantees an error.

**Comment by kevikanon** [comment]
Was googling for similar issues and found [this](https://github.com/dequelabs/axe-core/issues/1977#issuecomment-629271792). As the OP mentioned this is an issue caused by [Chromium Bug 1052872](https://bugs.chromium.org/p/chromium/issues/detail?id=1052872). So I did a little workaround in my chrome browser and it worked for me.

Here's what I did:

1. Go to [chrome://flags](chrome://flags) (chrome experimental features) page on your chrome browser.
2. Search for `Extensions on chrome:// URLs` flag and enable it.
3. Restart the browser.

Alternatively you can go directly to [chrome://flags/#extensions-on-chrome-urls](chrome://flags/#extensions-on-chrome-urls) and enable the flag.

I think this will work on other chromium based browsers too. You need to replace the name of the browser on flag url for other chromium browsers. e.g. [edge://flags](edge://flags) or [brave://flags](brave://flags).

_Warning: I do not know whether this poses any risk or security vulnerability, so you are proceed at your own risk if you want to!_

**Comment by jgaehring** [comment]
Just documenting a super-weird variation of this issue in case anyone else encounters something similar....

My error was:

`
DevTools failed to load source map: Could not load content for chrome-extension://eehlbikncmbbmebknibmlajbmhjiepbh/main.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
`

That `main.map` bit really perplexed me and was super hard to pin down (good luck searching `main.*`!), but eventually with some help from [this SO answer](https://stackoverflow.com/a/62761650/1549703) I was able to find it in my Chrome extensions by searching that hash, which turned up this completely unrelated extension, [`highlight-to-google-calendar`](https://github.com/blackwood/highlight-to-google-calendar) by @blackwood (no shade intended, just pinging you in case this is of interest, love the extension btw!), which I just so happened to install yesterday. Switching this extension's "Site access" settings from "On all sites" to "On click" resolved the issue for me.

Still I can't understand why another extension would get picked up by Vue DevTools... :thinking:

**Comment by isimmons** [comment]
OP states this is being served by webpack-dev-server so should not be a production build. I just ran into this same issue with a simple webpack project, no Vuejs and got the same warnings in chrome devtools because webpack config needs to be told to create source maps. In case this helps anyone else I added the devtools option to my webpack.config.js
```js
const path = require('path');

module.exports = {
  mode: 'development',
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'bundle.js',
  },
  devtool: 'eval-source-map',
  watch: true,
};
```

Other devtool options [Here]('https://webpack.js.org/configuration/devtool/')

**Comment by DenisLopatin** [comment]
`devtool: 'eval-source-map'` It works. Thanks!
