### ISSUE TITLE
Vue.js not detected

### ISSUE THREAD

**Issue by hrqmonteiro** [vuejs/devtools#1478]
### Version
6.0.0-beta.13

### Browser and OS info
Firefox and Chrome

### Steps to reproduce
Just trying to use the addon and it doesn't detect Vue

### What is expected?
To detect Vue

### What is actually happening?
Not detecting vue..

Tried on Firefox, Chrome, Brave. Tried CLI, CDN, Npm.

It doesn't detect.

**Comment by arpan-sharma26** [comment]
I hope you were getting this error, Like me

![image](https://user-images.githubusercontent.com/35891294/121585161-e51c5b00-ca4f-11eb-9869-1ca9bd1a1d05.png)

What I did was, just simply restart (re-run) your project and then it'll start working.

![image](https://user-images.githubusercontent.com/35891294/121585778-98854f80-ca50-11eb-8e22-772cb735eff4.png)

**Comment by epicfail169** [comment]
Same problem here at Win10. Didnt work in FF and Chrome.

**Comment by Akryum** [comment]
Did you follow [those steps](https://devtools.vuejs.org/guide/faq.html#the-vue-devtools-don-t-show-up)?

**Comment by hrqmonteiro** [comment]
> Did you follow [those steps](https://devtools.vuejs.org/guide/faq.html#the-vue-devtools-don-t-show-up)?

Followed all of this, still doesn't work in any of the browsers existent. I am having to learn Vue without this Dev Tools.

**Comment by smavrommatis** [comment]
I also have the same issue with self hosted file. I Just referenced https://unpkg.com/browse/vue@3.1.5/dist/vue.global.js this file.
I also downloaded it and referenced it from local path.
With a vue-cli project installation it works perfectly. The issue is with self hosted files <script src=...

No errors in the console

**Comment by mikebernal** [comment]
@hrqmonteiro check their legacy readme https://github.com/vuejs/devtools/tree/legacy

**Comment by Raiondesu** [comment]
Bumped into this too, Vue 3 is not detected by the devtools (chrome).

After a little investigation, I think there are 2 possible reasons for this:

1. It seems as if the detection "Method 3" might be failing, because, in Vue 3, elements bound to vue apps have the `__vue_app__` property instead of `__vue__`, which the code looks for.

    https://github.com/vuejs/devtools/blob/7273c9a9fca2d54134f92c1e8caed59b51d0818c/packages/shell-chrome/src/detector.js#L43-L51

    ![image](https://user-images.githubusercontent.com/19854420/129942831-962c19bb-d82e-43bd-9855-27847fe64496.png)



2. "Method 2" can also fail, because when Vue 3 is used as a native ES6 browser module (i.e. `import from 'https://unkpg/vue@next'`), it doesn't pollute the `window`, as the detection scripts expects it to.

    https://github.com/vuejs/devtools/blob/7273c9a9fca2d54134f92c1e8caed59b51d0818c/packages/shell-chrome/src/detector.js#L31-L41

    ![image](https://user-images.githubusercontent.com/19854420/129942243-c82d3428-ae1f-4537-8632-255a61faa19e.png)

---

My Vue 3 setup in this case is bundler-free, Vue is imported in a `type="module"` script, from the esm bundle at `https://unpkg.com/vue@3.1.5/dist/vue.runtime.esm-browser.prod.js`.

In projects where Vue is processed via Webpack or Vite, detection seems to work fine for me.

I use `6.0.0-beta.15`.

**Comment by wh1tenoise** [comment]
Hi, I do encounter this, too
Current version `6.0.0-beta.18` is in use but VueJS is not detected when imported directly from `https://unpkg.com/vue@next`.

**Comment by cimenta** [comment]
I am getting "not detected" for the latest Vue and the latest plugin version for both firefox and chrome browsers. 

I am getting "not detected" for both

1) my Google Application Script web
https://script.google.com/macros/s/AKfycbxfIx0rZbrlFcK0frgdqxb7QjXKkbPEGL0DHqRWpvgjGrDgc2fZ2NYBxHJomFu0tt-EPQ/exec

2) and this sample table Vue application I found https://ygnl5.csb.app/

BUT if I go mouse click on both pages and then inspect 
1) does NOT show Vue tab
2) SHOWS Vue tab

So my conclusion is that iFrame that Google adds is causing the troubles

**Comment by cimenta** [comment]
why was this case closed? It is resolved?
