### ISSUE TITLE
[Nuxt] [Vuex] Devtools don't show updated values in Vuex inspector

### ISSUE THREAD

**Issue by volkov-aleksandr** [vuejs/devtools#1703]
### Version
6.0.5

### Browser and OS info
Chrome 98

### Steps to reproduce
https://bitbucket.org/1creator/vue-devtools-bug/src/master/

### What is expected?
Filled state

### What is actually happening?
State has initial values
![image](https://user-images.githubusercontent.com/84247924/153449560-5b9c049f-cba6-48ee-9a96-15cac1f8988a.png)

---
We use Nuxt JS 2 for SSR. 
Action nuxtServerInit at store/index.js updates auth module state with new value, which rendered on page and can be accessed via $nuxt.$store.state.auth.user. But devtools says that user state is null.

With devtools version 5 everything is fine.

**Comment by urbgimtam** [comment]
Exactly my use case. Suffering from the same issue.

**Comment by akadlec** [comment]
Same here. Had to do rollback to 5.3 version. It look like author is not testing it for vue2!

**Comment by Akryum** [comment]
@akadlec I'm not an army of testers to try out all the possible combinations of libraries and tools the millions different projects use.

**Comment by geoidesic** [comment]
This is also broken for me. Vuex state does not update, only shows initial state. I have no idea how to create an example of this because I don't now what's causing it. It works on one app but not on my other app. I am using the following plugins:

[`vuex-persist`](https://github.com/championswimmer/vuex-persist)
[`vuex-reststate`](https://github.com/reststate/reststate-vuex)
[`vuex-map-fields`](https://github.com/maoberlehner/vuex-map-fields)

**Comment by geoidesic** [comment]
> Same here. Had to do rollback to 5.3 version. It look like author is not testing it for vue2!

@akadlec can you please post links for how you managed to rollback?

**Comment by akadlec** [comment]
@geoidesic you could find old versions here: https://www.crx4chrome.com/crx/271395/

**Comment by Akryum** [comment]
Read [the documentation](https://devtools.vuejs.org/guide/installation.html).
