### ISSUE TITLE
Devtools not work when use $mount append custom Component

### ISSUE THREAD

**Issue by defghy** [vuejs/devtools#1710]
### Version
6.0.2

### Browser and OS info
chrome 96

### Steps to reproduce
```javascript

// vue2 
const instance = new Vue.extend({...})({
        propsData: {...},
});
document.body.appendChild(instance.$mount().$el);

// @vue/composition-api method
const a = createApp({...}, {...}).mount();
document.body.appendChild(a.$el);

```

6.0.*
![image](https://user-images.githubusercontent.com/5386958/153559543-1bc8febb-0970-472a-8674-233d20478682.png)

5.3.4
![image](https://user-images.githubusercontent.com/5386958/153559800-59031433-c43b-4e2c-bda3-29f4dc2d74c1.png)

### What is expected?
should detect modalDialog.vue

### What is actually happening?
no modalDialog.vue

**Comment by defghy** [comment]
Thanks from replying, I tried app selector, only 1 app1 exist

![image](https://user-images.githubusercontent.com/5386958/153700659-905ee09f-1233-402f-a073-08f1cd75b535.png)


Here is repro to this issue
https://github.com/defghy/demos/tree/master/issues/web

try to access url
```
http://localhost:8081/devtool-inspect
```

click the button and try to inspect the dialog

**Comment by MasterMonki** [comment]
I am experiencing the same issue. V5 worked fine, but I can longer view any dynamically created components since the Apps don't show in the selector.  Oddly, I'm quite certain it showed the additional App 3 on just the very first page load upon V6 being auto-updated, but I've been never been able to get it to reappear even after reboot.  My code is the same, as I do a Vue.extend() and append an element in the DOM for the purpose of opening a Modal Dialog.  I will need to revert to V5 for now.

- Chrome Version 98.0.4758.80 (Official Build) (x86_64)
- Vue 6.06

**Comment by troygilbert** [comment]
I'm encountering the issue as well. The app list updates the first time, but doesn't update again until the browser window is closed and re-opened.
