### ISSUE TITLE
Endless "Slave init complete Slave loading data" console logs

### ISSUE THREAD

**Issue by jarrodwhitley** [vuejs/devtools#1749]
### Version
8.1.5

### Browser and OS info
NativeScript-Vue with Electron

### Steps to reproduce
- install/import nativescript-vue-devtools via `import VueDevtools from 'nativescript-vue-devtools';`
- configure vue-devtools for my ip `Vue.use(VueDevtools, {host: 'xxx.xxx.x.xx'});`
- run `tns run ios`

### What is expected?
I expect not to see the pictured console logs since it this issue was supposed to be solved by [this commit](https://github.com/vuejs/devtools/commit/deb5f0ec00169ac840f53c2823ecbdeea020927f). 

![Screen Shot 2022-02-17 at 1 49 53 PM](https://user-images.githubusercontent.com/11711674/154559688-b11680ac-4c73-40ad-bf20-7b4155652f7a.png)

### What is actually happening?
I am seeing the pictured console logs

**Comment by Akryum** [comment]
Looking at `nativescript-vue-devtools`, it imports the `@vue/devtools` package (the `shell-electron` folder in this repo):

<img width="1018" alt="Screenshot 2022-02-17 at 21 29 52" src="https://user-images.githubusercontent.com/2798204/154565519-b2ba5e31-2e96-4f01-8051-838b42e23571.png">

The main file is `index.js`:

<img width="833" alt="Screenshot 2022-02-17 at 21 31 16" src="https://user-images.githubusercontent.com/2798204/154565698-debe512b-3e4d-4db0-a982-3441e3ecfb9d.png">

The `index.js` imports the built files (in the `build` folder):

<img width="691" alt="Screenshot 2022-02-17 at 21 31 43" src="https://user-images.githubusercontent.com/2798204/154565747-6673d957-cfc0-42b4-9133-7af3b51962ec.png">

The built files don't contain the console.logs. So the only possible explanation is that you are using an older version from before the fix was implemented.

**Comment by jarrodwhitley** [comment]
```
 "@vue/devtools": "^5.3.4",
 "nativescript-vue-devtools": "^1.5.1",
```

I see. It looks like I may indeed be on an older version of devtools.

**Comment by jarrodwhitley** [comment]
I installed that version while following[ these instructions](https://nativescript-vue.org/en/docs/getting-started/vue-devtools/). So maybe that's the version that nativescript-vue supports. I'll try upgrading and see if it fixes the issue.

**Comment by jarrodwhitley** [comment]
So I reinstalled vue-devtools, but I didn't specify the version and now those console logs are gone. Thanks for your help!
