### ISSUE TITLE
Hide layers

### ISSUE THREAD

**Issue by Tofandel** [vuejs/devtools#1898]
### Version
6.1.4

### Browser and OS info
Chrome 102

### Steps to reproduce
Go to timeline, click on "hide a layer"

### What is expected?
The entry to stay in the list but be hidden in the timeline chart

### What is actually happening?
There is no way to unhide a layer, the entry in the list is gone forever

**Comment by Akryum** [comment]
Add the layer back from the layers list in the top right toolbar.

**Comment by mesqueeb** [comment]
@Akryum I just want to give extra feedback that this "layers list" is very hard to find. I was confused as well and spend 10 minutes looking how to bring back the hidden layer. : D

there's so much room BELOW the actual layers, maybe you could add a button there as well that says "toggle layers" ?

something like this:
<img width="1085" alt="179338376-cec4af82-a66b-48a8-9b45-ceef405159cc" src="https://user-images.githubusercontent.com/3253920/179338423-85163526-6916-4617-bcc1-7a0c1592c1a0.png">

**Comment by TrentBrown** [comment]
I too wasted time trying to get my "layers" back. It was only by Googling and finding this very bug report that I discovered from the OP how to get them back!

Please follow his suggestion and put something in the layers panel. Maybe just put the layer icon there instead of way up in upper right corner. It sure seems to belong to the layers panel

Thanks in advance
