### ISSUE TITLE
highlight updates 

### ISSUE THREAD

**Issue by hqzh** [vuejs/devtools#862]
### What problem does this feature solve?
highlight updates 

### What does the proposed API look like?
highlight updates

**Comment by Ky6uk** [comment]
Ohh, I was surprised it's not implemented yet. :)
That feature is very convenient in React dev tools.

**Comment by yuichkun** [comment]
In case anyone is in need for this feature like **right now**, 

I created a library that does this: 

[vue-devtool-flash-updates](https://github.com/yuichkun/vue-devtool-flash-updates)
![](https://github.com/yuichkun/vue-devtool-flash-updates/raw/master/misc/live-demo-screenshot.gif)

If it's ever needed, I would be more than happy to port it to this library.

**Comment by blaadje** [comment]
I created a little plugin in my own application if ever someone wants to make library or something _(I myself do not have time to maintain / contribute library)_ cf https://github.com/blaadje/Todolist/pull/103/files

PS: cc @yuichkun I did canvas drawing instead of adding class to elements in order to avoid issues _(inspired by react-devtools)_
